import { ReactNode } from 'react';

import './globals.css';
import { Selector } from './components/selector';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' data-theme='cmyk'>
      <body className='bg-base-100 text-neutral'>
        <div className='flex flex-col items-center'>
          <Selector />
          <div className='max-w-screen-md min-h-[100vh] w-full flex flex-col'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
